name: 'Build godot'
description: 'Build godot'

inputs:
  channel:
    description: 'Channel to build'
    required: true
    default: 'windows'
  output:
    description: 'Output directory'
    required: true
  game-folder:
    description: 'Directory of the game'
    default: '.'
  password:
    description: 'Password for the files'
    required: false

outputs:
  game:
    description: 'Game name'
    value: ${{ steps.game-name.outputs.game }}

runs:
  using: "composite"
  steps:
    - id: game-name
      run: |
        NAME="$(cat $FOLDER/project.godot | grep config/name | awk -F'"' '{print $2}')"
        echo "game=$NAME" >> $GITHUB_OUTPUT
      shell: bash
      env:
        FOLDER: ${{ inputs.game-folder }}
    - name: Build
      id: build
      run: |
        mkdir -v -p $OUTPUT/$CHANNEL

        FILE="main"
        EXT=""
        if [ "$CHANNEL" = "web" ]; then
          FILE="index"
          EXT=".html"
        elif [ "$CHANNEL" = "linux" ]; then
          EXT=".x86_64"
        elif [ "$CHANNEL" = "windows" ]; then
          EXT=".exe"
        fi

        godot --verbose --headless --path "$FOLDER" --export-release "$CHANNEL" "$(pwd)/$OUTPUT/$CHANNEL/$FILE$EXT"
      shell: bash
      env:
        CHANNEL: ${{ inputs.channel }}
        OUTPUT: ${{ inputs.output }}
        FOLDER: ${{ inputs.game-folder }}
    
    - run: wget https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x64.exe
      shell: bash
      if: ${{ inputs.channel == 'windows' }}
    - run: rcedit-$ARCH.exe $OUTPUT/main.exe --set-icon icon.ico 
      shell: bash
      if: ${{ inputs.channel == 'windows' }}
      env:
        OUTPUT: ${{ inputs.output }}

    - run: |
        if [ -z "$password" ]; then
          zip -r $output -j $folder
        else
          zip -r $output -e -P "$password" -j $folder
        fi
      shell: bash
      env:
        folder: ${{ inputs.output }}/${{ inputs.channel }}
        password: ${{ inputs.password }}
        output: ${{ inputs.output }}/${{ steps.game-name.outputs.game }}-${{ inputs.channel }}.zip